config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  get "/u/:username", to: 'public#profile', as: :profile
  
  resources :communities do
    resources :posts, :except => [:index]
  end

  resources :subscriptions, except: :destroy
  delete '/subscriptions/:community_id', to: 'subscriptions#destroy'
  post '/subscriptions/:community_id', to: 'subscriptions#create'

  resources :comments, only: [:create, :destroy]
  
  get '/s/:slug', to: 'links#show'

  post '/posts/vote', to: 'votes#create' 

  #default parameter will soon sort by time
  get '/:sort(/:time)', to: 'posts#index', :defaults => { :time => 'id' } 

  root to: 'posts#index', sort: "front_page"
  
  get '*path' => redirect('/')


end

app/models/post.rb
class Post < ActiveRecord::Base
    extend FriendlyId
    friendly_id :community_id, use: :slugged
    belongs_to :account
    belongs_to :community
    has_many :comments, dependent: :destroy
    has_many :votes, dependent: :destroy
    validates_presence_of :title, :content, :account_id, :community_id
    has_rich_text :content

    def score
    # difference between upvotes and downvotes
        if self.upvotes > 0 || self.downvotes > 0
            self.upvotes > 0 ? (self.upvotes - self.downvotes) : (self.downvotes * -1)
        else
            0
        end
    end

    def percentage_upvoted
        if self.upvotes > 0 || self.downvotes > 0  
            ((self.upvotes.to_f)/(self.upvotes.to_f + self.downvotes.to_f))*100
        elsif self.upvotes == 0 && self.downvotes == 0
            0.0
        end
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_account!, except: [ :index, :show ]
    before_action :set_post, only: [:show]
    before_action :auth_subscriber, only: [:new]
    helper_method :params
    before_action :check_params, only: [:index]

    def index
        cookies[:moon] ||= "dark mode off"
        
        if account_signed_in?
            
        elsif params[:sort] === "front_page"
            params[:sort] = "top"
        end

        subscriptions = Subscription.where(account_id: current_account)
        front_page_posts = Array.new
        subscriptions.each { |subscription|
            if Community.find(subscription.community_id).posts === []

            else
                front_page_posts.push(Community.find(subscription.community_id).posts)
            end
        }

        if params[:sort] === "new"
            # time parameter will eventually be used to sort by time rather than order
            @posts = Post.order("#{params[:time]} DESC").limit(20)
        elsif params[:sort] === "front_page"
            front_page_posts = front_page_posts.flatten
            @posts = front_page_posts.sort_by{|obj| -obj.upvotes}
        elsif params[:sort] === "top"
            @posts = Post.all.order("upvotes DESC")
        end

        @sort = params[:sort]
        @url = request.original_url
        @communities = Community.all.order(id: :desc).limit(5)
    end

    def show 
        @link = Link.find_by(url: request.original_url) || Link.create(url: request.original_url)
        @comment = Comment.new
        @subscription = Subscription.new
        @is_subscribed = account_signed_in? ? Subscription.where(community_id: @post.community.id, account_id: current_account.id).any? : false
        @subscribers_count = @post.community.subscribers.count
    end

    def new
        @community = Community.find(params[:community_id])
        @post = Post.new
    end

    def create
        @post = Post.new post_params

        @post.account_id = current_account.id
        @post.community_id = Community.find_by(slug: params[:community_id]).id
        @post.slug = @post.title.downcase.tr_s(' ', '_').gsub(".","").gsub("?", "").gsub("'", "").gsub("!", "").gsub("__", "_").gsub("_-_", "_") + "_" + SecureRandom.hex(4)
        @community = Community.find_by(slug: params[:community_id])
        if @post.save
            link = Link.create(url: "https://discussionhub-51a7c53ae2c9.herokuapp.com/communities/#{@post.community.url}/posts/#{@post.slug}")
            @vote = Vote.new
            @vote.account_id = current_account.id
            @vote.post_id = @post.id
            @vote.upvote = true
            @vote.save
            @vote.account.increment!(:karma, 1)
            redirect_to community_post_path(@post.community.url, @post)
        else
            @community = Community.find_by(slug: params[:community_id])
            render :new 
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy

        if @post.destroyed?
            respond_to do |format|
                format.js {
                    render "posts/delete"
                }
            end
        end

    end

    private

    def set_post
        @post = Post.includes(:comments).friendly.find(params[:id])
    end

    def auth_subscriber
        @community = Community.find_by(slug: params[:community_id])
        unless Subscription.where(community_id: @community.id, account_id: current_account.id).any?
            redirect_to community_path(@community), flash: {danger: "You aren't subscribed to this community"}
        end
    end

    def post_params
        params.require(:post).permit(:title, :content)
    end

    def check_params
        if ['front_page', "top", "new"].include? params[:sort]

        else
            redirect_to root_path
        end
    end

    

end

app/helpers/posts_helper.rb
module PostsHelper

    def postSortSelection(url, id, sort)
        if url === "https://discussionhub-51a7c53ae2c9.herokuapp.com/new" && id === "new"
            "override"
        elsif url === "https://discussionhub-51a7c53ae2c9.herokuapp.com/" && id === "front_page" && sort === "front_page" 
            "override"
        elsif url === "https://discussionhub-51a7c53ae2c9.herokuapp.com/top" && id === "top" && sort === "top"
            "override"
        elsif url === "https://discussionhub-51a7c53ae2c9.herokuapp.com/" && id === "top" && sort === "top"
            "override"
        end
    end

    def profile?(controller)
        if controller == "posts"
            "px-3"
        end
    end

end

app/views/posts/_comments.html.erb
<% comments.each do |comment| %>
  <div id="comment-<%= comment.id %>" class="col-8 card p-3 w-100 pb-0 mx-0 mb-2">
    <div class="d-flex justify-content-between">
      <div><%= link_to comment.account.username, profile_path(comment.account.username), class: "text-decoration-none" %> <%= tag.small time_ago_in_words comment.created_at %> <small>ago</small></div>
    </div>
    <%= simple_format comment.message %>
    <p class ="d-flex mb-2">
      <% if account_signed_in? %>
        <% if comment.account_id === current_account.id %>
          <small><%= link_to "Delete", comment_path(comment.id), remote: true, method: :delete, data: { confirm: 'Are you sure you want to delete this?' }, style:"color: rgb(102,102,102); font-weight: 700", class: "text-decoration-none" %></small>
        <% end%>
      <% end%>
    </p>
  </div>
<% end %>

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-sm-8">
    <%= form_for [@community, @post] do |form| %>
      <div class="form-label">
        <%= label_tag :title %>
        <%= form.text_field :title, class: "form-control" %>
      </div>
      <div class="field">
        <%= form.label :content %>
        <%= form.rich_text_area :content, class: "form-control customized-min-height" %>
      </div>
      <%= form.submit "Submit", class: "btn btn-primary mt-1 mb-3" %>
    <% end %>
  </div>
</div>

app/views/posts/_lists.html.erb
<% @count = 0 %>
<% if @posts.length === 0 && params[:controller] === "posts" %>
  <% @posts = Post.all.order("upvotes DESC") %>
  <div class="d-flex justify-content-center"><strong>Showing All Posts.</strong></div>
  <div class="d-flex justify-content-center mb-2"><strong>Join communities to see their posts on your home page.</strong></div>
<% end %>
<% @posts.each do |post| %>
  <div id="post-<%= post.id %>" class="card p-3 mb-3">
    <div class="row">
      <div class="mt-2 col-sm-1 px-2 col-2">
        <div class="d-flex justify-content-between align-items-center">
          <small style="color: rgb(102,102,102); padding-right: 10px" class="d-flex align-items-center"><%= @count += 1 %> </small>
          <%= render partial: "posts/post_votes", locals: { post: post} %>
        </div>
      </div>
      <div class="col-sm-9 col-9">
        <h4 class="mb-0">
          <%= link_to post.title, community_post_path(post.community.url, post), class: "text-decoration-none" %>
        </h4>
        <p class="mb-0">
          <small>Submitted <%= time_ago_in_words post.created_at %> ago by  <%= link_to post.account.username, profile_path(post.account.username), class: "text-decoration-none"  %> to <%= link_to post.community.url, post.community, class: "text-decoration-none" %>  </small>
        </p>
        <p class="d-flex">
          <small class="post-small-links"><%= link_to (pluralize post.total_comments, "comment"), community_post_path(post.community_id, post, anchor: 'post-comments'), class: "text-decoration-none"  %> </small>
          <% if account_signed_in? %>
            <% if post.account_id === current_account.id %>
              <small class="mx-2 post-small-links"><%= link_to "delete", community_post_path(post.community_id, post.id), remote: true, method: :delete, data: { confirm: 'Delete this post? This is irreversible.' }, class: "text-decoration-none" %></small>
            <% end%>
          <% end%>
        </p>
        <p class="mb-0">
          <%= truncate(strip_tags(post.content.to_s), length: 140) %>
          <% if post.content.to_s.length > 140 %>
            <%= link_to "see more", community_post_path(post.community.url, post), class: "text-decoration-none" %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_post_votes.html.erb
<div id="vote-actions-<%= post.id %>" data-account="<%= account_signed_in? %>" data-id="<%= post.id %>" class="w-50 d-flex flex-column align-items-center vote">
  <div id="up-arrow" class="fa fa-arrow-up mb-1 upvote <%= is_upvoted post %>"></div>
  <div class="text-center score"><strong><%= post.score %></strong></div>
  <div id="down-arrow" class="fa fa-arrow-down mt-1 downvote <%= is_downvoted post %>"></div>
</div>

app/views/posts/_sort_buttons.html.erb
<div class="d-flex align-items-center px-0">
  <% if account_signed_in? %>
    <span class="px-2 <%= postSortSelection @url, "front_page", @sort %>"><%= link_to "Home", root_path, class: "text-decoration-none" %></span>
    <span class="px-3 <%= postSortSelection @url, "top", @sort %>"><%= link_to "Top", root_path + "top", class: "text-decoration-none" %></span>
  <% else %>
    <span class="px-3 <%= postSortSelection @url, "top", @sort %>"><%= link_to "Top", root_path, class: "text-decoration-none" %></span>
  <% end %>
  
  <span class="px-2 <%= postSortSelection @url, "new", @sort %>"><%= link_to "New", root_path + "new", class: "text-decoration-none" %></span>
</div>

app/views/posts/delete.js.erb
$("#post-<%= @post.id %>").remove()
window.location.replace("<%= community_path(@post.community) %>");

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render partial: "form"  %>

app/views/posts/index.html.erb
<% content_for :title do %>
  <% if request.original_url == "https://discussionhub-51a7c53ae2c9.herokuapp.com/new" %>
    newest submissions
  <% elsif request.original_url == "https:///" %>
    discussionhub: the front page of the internet
  <% elsif request.original_url == "https://discussionhub-51a7c53ae2c9.herokuapp.com/top" %>
    top scoring links: all
  <% end %>
<% end %>

<% content_for :header_info do %>
  <p role="button" class="h4 mb-2 mt-2 d-flex align-items-center"><%= link_to "DiscussionHub", root_path, class: "text-decoration-none" %></p>
<% end %>

<div class="row">
  <div class="col-sm-8 d-none d-sm-inline">
    <%= render partial: "posts/lists" %>
  </div>
  <div class="col-sm-4 d-none d-sm-inline">
    <div class="mb-2"><%= link_to "Create New Community", new_community_path, class: "w-100 btn btn-primary" %></div>
  </div>
  <div class="d-sm-none">
    <div class="mb-2"><%= link_to "Create New Community", new_community_path, class: "w-100 btn btn-primary" %></div>
  </div>
  <div class="d-sm-none">
    <%= render partial: "posts/lists" %>
  </div>
</div>

app/views/posts/new.html.erb
<%= title "#{@community.url}: submit" %>
<% content_for :header_info do %>
  <p role="button" class="h4 mb-2 mt-2 d-flex align-items-center"><%= link_to "DiscussionHub", root_path, class: "text-decoration-none" %></p>
  <%= link_to "#{@community.url}: submit", @community, class: "h6 mb-2 mt-2 mx-2 text-decoration-none text-dark fw-bold align-items-center d-flex text-nowrap" %>
<% end  %>
<h2>New Post</h2>
<%= render partial: "form"  %>

app/views/posts/show.html.erb
<%= title @post.title %>
<% content_for :header_info do %>
  <p role="button" class="h4 mb-2 mt-2 d-flex align-items-center"><%= link_to "DiscussionHub", root_path, class: "text-decoration-none" %></p>
  <%= link_to @post.community.url, @post.community, class: "h6 mb-2 mt-2 mx-2 text-decoration-none text-dark fw-bold align-items-center d-flex" %>
<% end %>
<div class="row mb-2">
  <div class="col-sm-5 d-inline d-sm-none">
    <%= render partial: "communities/info", locals: { community: @post.community } %>
  </div>
  <div class="col-sm-8">
    <div class="row mt-2">
      <div class="d-flex">
        <div>
          <div class="mb-1 d-flex flex-row">
            <div style="margin-left: 15px; width: 10px">
              <%= render partial: "posts/post_votes", locals: { post: @post} %>
            </div>
            <div class="mx-3 d-flex flex-column justify-content-center align-items-start justify-con">
              <%= link_to @post.title, community_post_path(@post.community_id, @post), class: "h4 mb-0 text-decoration-none" %>
              <small>submitted <%= time_ago_in_words @post.created_at %> ago by <%= link_to @post.account.username,
                profile_path(@post.account.username), class: "text-decoration-none" %>
              </small>
              <div>
                <small id="post-comment" class="post-small-links">
                  <%= pluralize @post.total_comments, "comment" %>
                </small>
                <% if account_signed_in? %>
                  <% if @post.account_id===current_account.id %>
                    <small class="mx-2 post-small-links">
                      <%= link_to "delete" , community_post_path(@post.community_id, @post.id), remote: true, method: :delete,
                        data: { confirm: 'Delete this post? This is irreversible.' }, class: "text-decoration-none" %>
                    </small>
                  <% end%>
                <% end%>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row p-2">
      <div class="mb-0 p-3 card rounded">
        <%= @post.content %>
      </div>
    </div>
    <div class="row">
      <p class="mb-0 h5">Leave a comment</p>
    </div>
    <div class="row">
      <%= form_for @comment, remote: true, method: :post, html: {id: "new_comment" } do |f| %>
        <%= f.hidden_field :post_id, value: @post.id %>
        <div id="comment-form" class="form-label">
          <%= f.text_area :message, placeholder: "Type comment" , class: "form-control" %>
        </div>
        <%= f.submit "save" , class: "btn btn-sm btn-secondary mb-2" %>
      <% end%>
    </div>
    <div class="row">
      <div id="post-comments">
        <%= render partial: "posts/comments" , locals: {comments: @post.comments.order("id")}%>
      </div>
    </div>
  </div>
  <div class="col-sm-4 d-none d-sm-block">
    <div class="row">
      <div>
        <p class="mb-0 bg-white card-body">
          <strong>this post was submitted on <%= @post.created_at.strftime("%d %b %Y") %></strong>
          <div class="d-flex align-items-end card-body bg-white pt-0">
            <p class="mb-0">
              <strong><%=pluralize @post.score, "point" %> <small> </strong> (<%= @post.percentage_upvoted.truncate %>% upvoted)</small>
            </p>
          </div>
          <div class="d-flex align-items-end card-body bg-white pt-0">
            <p class="mb-0 text-break">
              <strong><small><%= link_to @link.short.gsub("https://", ""), @link.short, class: "text-decoration-none" %></small></strong>
            </p>
          </div>
        </p>
      </div>
    </div>
    <div class="row">
      <h5 class="mb-1">
        <%= @post.community.url %>
      </h5>
      <div class="d-flex align-items-center">
        <% if @is_subscribed %>
          <span><%= button_to "leave", subscription_path(@post.community.id), method: :delete, class: "btn btn-sm btn-danger", style:"font-size: 70%" %></span>
        <% else %>
          <%= button_to "join", subscription_path(@post.community.id), method: :create, class: "btn btn-sm btn-success", style:"font-size: 70%" %>
        <% end %>
        <span style="font-size: 70%">&nbsp;<%= pluralize @post.community.subscribers.count, "subscriber" %></span>
      </div>
    </div>
  </div>
</div>