config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  get "/u/:username", to: 'public#profile', as: :profile
  
  resources :communities do
    resources :posts, :except => [:index]
  end

  resources :subscriptions, except: :destroy
  delete '/subscriptions/:community_id', to: 'subscriptions#destroy'
  post '/subscriptions/:community_id', to: 'subscriptions#create'

  resources :comments, only: [:create, :destroy]
  
  get '/s/:slug', to: 'links#show'

  post '/posts/vote', to: 'votes#create' 

  #default parameter will soon sort by time
  get '/:sort(/:time)', to: 'posts#index', :defaults => { :time => 'id' } 

  root to: 'posts#index', sort: "front_page"
  
  get '*path' => redirect('/')


end

app/models/community.rb
class Community < ActiveRecord::Base
   extend FriendlyId
   friendly_id :url, use: [:slugged, :finders]  
   belongs_to :account
   validates_presence_of :url, :rules, :summary
   validates :url, uniqueness: true
   has_many :posts, dependent: :destroy
   has_many :subscriptions, dependent: :destroy 
   has_many :subscribers, through: :subscriptions, source: :account
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
    before_action :authenticate_account!, except: [ :index, :show ]
    before_action :set_community, only: [:show]

    def index
        @communities = Community.all
        @communities_count = Community.all.count
        @subscriptions = account_signed_in? ? Subscription.where(account_id: current_account.id) : nil
    end

    def show 
        @posts = @community.posts.order(id: :desc)
        @subscribers_count = @community.subscribers.count
        @is_subscribed = account_signed_in? ? Subscription.where(community_id: @community.id, account_id: current_account.id).any? : false
        @subscription = Subscription.new
    end

    def new
        @community = Community.new
    end

    def create
        @community = Community.new community_params
        @community.account_id = current_account.id
        @community.slug = @community.url

        if @community.save
            @subscription = Subscription.new(community_id: @community.id)
            @subscription.account_id = current_account.id
            @subscription.save
            redirect_to community_path(@community)
        else
            render :new 
        end
    end

    private

    def set_community
        @community = Community.find(params[:id])
    end

    def community_params
        params.require(:community).permit(:name, :url, :summary, :rules)
    end

end

app/views/communities/_form.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= form_for @community do |form| %>
      <div class="form-label">
        <%= label_tag :url, "Name" %>
        <%= form.text_field :url, class: "form-control" %>
      </div>
      <div class="form-label">
        <%= label_tag :rules %>
        <%= form.text_area :rules, class: "form-control" %>
      </div>
      <div class="form-label">
        <%= label_tag :summary %>
        <%= form.text_area :summary, class: "form-control" %>
      </div>
      <%= form.submit "Submit", class: "btn btn-primary mb-3" %>
    <% end %>
  </div>
</div>

app/views/communities/_info.html.erb
<div class="dropdown">
  <button class="w-100 mb-2 btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    <%= community.url %> info
  </button>
  <ul class="dropdown-menu w-100" aria-labelledby="dropdownMenuButton1">
    <% if params[:controller] === "posts" %>
      <li class="dropdown-item">
        <p class="mb-0 bg-white card-body">
          <strong>this post was submitted on <%= community.created_at.strftime("%d %b %Y") %></strong>
          <div class="d-flex align-items-end card-body bg-white pt-0">
            <p class="mb-0">
              <strong><%= @post.score %> <small>points </strong> (<%= @post.percentage_upvoted.truncate %>% upvoted)</small>
            </p>
          </div>
          <div class="d-flex align-items-end card-body bg-white pt-0">
            <p class="mb-0">
              <strong><small><%= link_to @link.short.gsub("https://", ""), @link.short, class: "text-decoration-none" %></small></strong>
            </p>
          </div>
        </p>
      </li>
    <% end %>
    <% if @is_subscribed && params[:controller] === "communities" %>
      <li class="dropdown-item"><%= link_to "Create New Post", new_community_post_path(community.slug), method: :get, class: "w-100 btn btn-primary" %></li>
    <% end %>
    <li class="dropdown-item">
      <div class="card p-3">
        <div class="mb-2 h5">About</div>
        <div class="text-wrap" ><%= community.summary %></div>
        <div class="mb-2"><%= pluralize @subscribers_count, "member" %> </div>
      </div>
    </li>
    <li class="dropdown-item">
      <div class="card p-3">
        <div class="mb-2 h5">Rules</div>
        <%= simple_format community.rules %>
      </div>
    </li>
    <li class="dropdown-item">
      <% if @is_subscribed %>
        <div><%= button_to "Leave Community", subscription_path(community.id), method: :delete, class: "w-100 btn btn-sm btn-danger" %></div>
      <% else %>
        <%= link_to "Join Community", subscription_path(community.id), method: :create, class: "btn btn-success w-100" %>
      <% end %>
    </li>
  </ul>
</div>

app/views/communities/index.html.erb
<% content_for :title do %>
  communities
<% end %>
<% content_for :header_info do %>
  <p role="button" class="h4 mb-2 mt-2 d-flex align-items-center"><%= link_to "DiscussionHub", root_path, class: "text-decoration-none" %></p>
  <div class="d-flex mx-2 align-items-center fw-bold">communities</div>
<% end %>
<div class="row">
  <div class="d-sm-none">
    <div class="mb-2"><%= link_to "Create New Community", new_community_path, class: "w-100 btn btn-primary" %></div>
  </div>
  <div class="col-sm-8">
    <% if @communities.size > 0 %>
      <% @communities.each do |community| %>
        <div class="card p-3 pb-1 mb-2">
          <% if account_signed_in? %>
            <% if Subscription.where(community_id: community.id, account_id: current_account.id).length > 0 %>
              <div class="d-flex flex-row mb-2">
                <span><%= button_to "leave", subscription_path(community.id), method: :delete, class: "btn btn-sm btn-danger text-decoration-none", style:"font-size: 70%" %></span>
                <h4 class="mb-0 mx-2">
                  <%= link_to community.url, community, class: "text-decoration-none" %>
                </h4>
              </div>
            <% else %>
              <div class="d-flex flex-row mb-2">
                <span><%= button_to "join", subscription_path(community.id), method: :create, class: "btn btn-sm btn-success text-decoration-none", style:"font-size: 70%" %></span>
                <h4 class="mb-0 mx-2">
                  <%= link_to community.url, community, class: "text-decoration-none" %>
                </h4>
              </div>
            <% end %>
          <% else %>
            <h4 class="mb-2 mx-2">
              <%= link_to community.url, community, class: "text-decoration-none" %>
            </h4>
          <% end %>
          <div class="card p-2">
            <p class="mb-0"><%= community.summary %></p>
          </div>
          <div>
            <small class="post-small-links"><%= pluralize community.subscriptions.count, "subscriber" %></small>,
            <small class=" post-small-links">a community since <%= community.created_at.strftime("%m/%d/%Y") %></small>
          </div>
        </div>
      <% end %>
    <% else %>
      <h4>No Communities</h4>
    <% end %>
  </div>
  <div class="col-sm-4 d-none d-sm-inline">
    <% if account_signed_in? %>
      <div class="d-flex flex-column align-items-center">
        <div class="mb-2 w-100"><%= link_to "Create New Community", new_community_path, class: "w-100 btn btn-primary" %></div>
        <div>Home Feed Communities (<%= @subscriptions.count %>)</div>
      </div>
      <div class="list-group">
        <% @subscriptions.each do |subscription| %>
          <li class="list-group-item d-flex">
            <% if account_signed_in? %>
              <span><%= button_to "leave", subscription_path(subscription.community.id), method: :delete, class: "btn btn-sm btn-danger", style:"font-size: 70%" %></span>
            <% end %>
            <%= link_to subscription.community.url.capitalize, subscription.community, class: "text-decoration-none mx-2"  %>
          </li>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/communities/new.html.erb
<% content_for :header_info do %>
  <p role="button" class="h4 mb-2 mt-2 d-flex align-items-center"><%= link_to "DiscussionHub", root_path, class: "text-decoration-none" %></p>
<% end %>
<%= title "discussionhub: create a community" %>

<h2>New Community</h2>

<%= render partial: "form"  %>

app/views/communities/show.html.erb
<% content_for :title do %>
  <%= @community.url %>
<% end %>
<% content_for :header_info do %>
  <p role="button" class="h4 mb-2 mt-2 d-flex align-items-center"><%= link_to "DiscussionHub", root_path, class: "text-decoration-none" %></p>
  <%= link_to @community.url, @community, class: "h6 mb-2 mt-2 mx-2 text-decoration-none fw-bold text-dark align-items-center d-flex" %>
<% end %>

<div class="row mb-3">
  <div class="col-sm-5 d-inline d-sm-none">
    <%= render partial: "communities/info", locals: { community: @community } %>
  </div>
  <div class="col-sm-8">
    <%= render partial: "posts/lists", locals: { posts: @posts } %>
  </div>
  <div class="col-sm-4 d-none d-sm-inline">
    <div class="d-flex flex-column">
      <% if @is_subscribed %>
        <%= link_to "Create New Post", new_community_post_path(@community.slug), method: :get, class: "btn btn-primary float-end" %>
      <% else %>
        <%= link_to "Join Community", subscription_path(@community.id), method: :create, class: "btn btn-success float-end" %>
      <% end %>
      <div class="card p-3 mt-2">
        <div class="mb-2 h5">About</div>
        <div ><%= @community.summary %></div>
        <div class="mb-2"><%= pluralize @subscribers_count, "member" %> </div>
        <% if @is_subscribed %>
          <div><%= button_to "Leave Community", subscription_path(@community.id), method: :delete, class: "btn btn-sm btn-outline-danger" %></div>
        <% end %>
      </div>
      <div class="card p-3 mt-2">
        <div class="mb-2 h5">Rules</div>
        <%= simple_format @community.rules %>
      </div>
    </div>
  </div>
</div>