config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  get "/u/:username", to: 'public#profile', as: :profile
  
  resources :communities do
    resources :posts, :except => [:index]
  end

  resources :subscriptions, except: :destroy
  delete '/subscriptions/:community_id', to: 'subscriptions#destroy'
  post '/subscriptions/:community_id', to: 'subscriptions#create'

  resources :comments, only: [:create, :destroy]
  
  get '/s/:slug', to: 'links#show'

  post '/posts/vote', to: 'votes#create' 

  #default parameter will soon sort by time
  get '/:sort(/:time)', to: 'posts#index', :defaults => { :time => 'id' } 

  root to: 'posts#index', sort: "front_page"
  
  get '*path' => redirect('/')


end

app/views/layouts/_community_header.html.erb
<div id="community_header" style="font-size: 70%">
  <div class="row justify-content-around">
    <div style="white-space: nowrap" class="d-flex align-content-center col-8">
      <div class="dropdown d-flex align-items-center">
        <a href="#" style="font-size: 110%" class="text-decoration-none dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
          My Communities
        </a>
        <div class="mx-2">
          <%= render partial: "posts/sort_buttons" %>
        </div>
        <ul class="dropdown-menu p-0" aria-labelledby="dropdownMenuButton1">
          <% if account_signed_in? %>
            <% current_account.communities.order(:name).each do |community| %>
              <%= link_to community.url.upcase, community, class: "dropdown-item", style:"font-size: 60%" %>
            <% end %>
            <%= link_to "ALL COMMUNITIES", communities_path, class: "dropdown-item", style:"font-size: 60%; border-top: 1px dotted black" %>
          <% else %>
            <%= link_to "ALL COMMUNITIES", communities_path, class: "dropdown-item", style:"font-size: 60%" %>
          <% end %>
        </ul>
      </div>
    </div>
    <div style="white-space: nowrap"  class="col-3 d-flex justify-content-end align-items-center">
      <%= link_to "MORE »", communities_path, class: "text-decoration-none mt-1 mb-1", style: "font-size: 110%"%>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="font-small blue">
  <div class="text-center py-3">
    <a href="https://www.linkedin.com/in/john-tyler-finley/", target="_blank"> <i class="mx-3 fa-brands fa-2x fa-linkedin"></i></a>
    <a href="https://github.com/jfinley6", target="_blank"> <i class="mx-4 fa-brands fa-2x fa-github"></i></a>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div id="page-header" class="container">
  <div class="row">
    <div class="col-sm-6 col-7 d-flex">
      <%= yield :header_info %>
    </div>
    
    <div class="col-sm-6 col-5 float-end d-flex justify-content-end px-1 align-items-center">
      <% if account_signed_in? %>
        <div class="dropdown">
          <a href="#" class="btn btn-white dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_account.username %> (<span id="karma-header" style="color: <%= changeKarmaColor current_account.karma %>"><%= current_account.karma %></span>)
          </a>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <%= link_to "Profile" , profile_path(current_account.username), class: "dropdown-item" %>
            <%= link_to "Settings" , edit_account_registration_path , class: "dropdown-item" %>
            <%= link_to "Sign Out" , destroy_account_session_path, method: :get, class: "dropdown-item" %>
          </ul>
        </div>
      <% else %>
        <div>
          <%= link_to "Log In" , new_account_session_path, class: "btn btn-sm btn-outline-primary" %>
          <%= link_to "Sign Up" , new_account_registration_path, class: "btn btn-sm btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <% if cookies[:moon] == "dark mode off" %>
      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <% else %>
      <%= stylesheet_link_tag "application_dark", "data-turbo-track": "reload" %>
    <% end %>
    <%= javascript_include_tag :jquery, :jquery_ujs %>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application" %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>
  <body>
    <%= render partial: "layouts/community_header" %>
    <%= render partial: "layouts/header" %>
    <section style="background-color: #EBEBEB">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 pt-3">
            <script src="https://kit.fontawesome.com/e66ae3e757.js" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
            <%= yield %>
          </div>
        </div>
      </div>
    </section>
    <%= render partial: "layouts/footer" %>
  </body>
</html>